services:
  advent:
    build:
      context: ./
      target: php_aoc
    volumes:
      - ./:/srv/app
      - ./docker/conf.d/aoc.ini:/usr/local/etc/php/conf.d/aoc.ini
    environment:
      # Keep attention to that env variable
      PHP_IDE_CONFIG: serverName=advent
