version: '3'
services:
  advent:
    build:
      context: ./
    volumes:
      - ./:/var/www/advent:cached
      - ./docker/conf.d/aoc.ini:/usr/local/etc/php/conf.d/aoc.ini
    environment:
      # Keep attention to that env variable
      PHP_IDE_CONFIG: serverName=advent
